openapi: 3.0.1
info:
  title: buffer-loan-store
  description: API Definition of buffer-loan-proposal-list
  version: 1.0.0
servers:
- url: http://localhost:8290/v1/buffer-loan-proposals
paths:
  /:
    post:
      responses:
        default:
          description: Default response
